set(NEW_LIST_SEPARATOR "<|>")

string(REPLACE ";" "${NEW_LIST_SEPARATOR}" _OPENSSL_FETCH_INFO "${OPENSSL_1_1_FETCH_INFO}")

ExternalProject_Add(build_openssl_1_1
        BUILD_ALWAYS TRUE
        PREFIX     ${CMAKE_CURRENT_BINARY_DIR}/project-openssl-1_1
        DOWNLOAD_COMMAND ""
        SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/project-openssl-1_1
        INSTALL_DIR  ${BUILDING_INSTALL_PREFIX}
        DEPENDS build_zlib
        LIST_SEPARATOR "${NEW_LIST_SEPARATOR}"
        CMAKE_ARGS
            ${_PROPAGATE_BUILD_TYPE}
            -DCMAKE_MODULE_PATH=${BUILDING_CMAKE_MODULE_PATH}
            -DCMAKE_INSTALL_PREFIX=${BUILDING_INSTALL_PREFIX}
            -DBUILDING_INSTALL_PREFIX=${BUILDING_INSTALL_PREFIX}
            -DBUILDING_LIBRARY_ZLIB_LINK_TYPE=static
            -DOPENSSL_FETCH_INFO:string=${_OPENSSL_FETCH_INFO}
        )
