if (COMMON_LIBRARY_ROOT_STATIC)
    set(_TEMP_LIBRARY_DIR_PREFIX ${COMMON_LIBRARY_ROOT_STATIC})
else()
    set(_TEMP_LIBRARY_DIR_PREFIX ${BUILDING_INSTALL_PREFIX})
endif()

include(${_TEMP_LIBRARY_DIR_PREFIX}/lib/cmake/grpc/gRPCConfig.cmake)
set(gRPC_FOUND TRUE)
